name: Check Linting

on:
  workflow_dispatch:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install

      - name: Check Linting
        run: npm run lint

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test
